pipeline:
  build:
    image: dvitali/android-build:feb-20
    commands:
      - "mkdir -p /build/kernel/kitchen"
      - "chown -R $UID:$UID /build"
      - "git clone https://github.com/denysvitali/ramdisk-builder /build/kernel/ramdisk"
      - "ln -s ramdisk.cpio.gz /build/kernel/ramdisk/custom-initramfs.cpio.gz"
      - "ls -la /build/kernel/ramdisk/"
      - "git clone https://github.com/denysvitali/smaug-custom-initram /build/kernel/smaug-custom-initram"
      - "mkdir /build/kernel/linux-smaug"
      - "ln $PWD /build/kernel/linux-smaug"
      - "ls -la /build/kernel/"
      - "cd /kernel/ramdisk/"
      - "./build.sh"
      - "ls -la /kernel/ramdisk/"
      - "cd /kernel/linux-smaug/"
      - "make dragon_denvit_defconfig"
      - "bash getvendor.sh -f"
      - "make -j8"
      - "./build-image.sh"
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: /kernel/kitchen/*
