workspace:
  base: /kernel
  path: /linux-smaug
pipeline:
  build:
    image: dvitali/android-build:feb-20
    commands:
      - "mkdir -p /kernel/kitchen"
      - "git clone https://github.com/denysvitali/ramdisk-builder /kernel/ramdisk"
      - "ln -s ramdisk.cpio.gz /kernel/ramdisk/custom-initramfs.cpio.gz"
      - "ls -la /kernel/ramdisk/"
      - "git clone https://github.com/denysvitali/smaug-custom-initram /kernel/smaug-custom-initram"
      - "ls -la /kernel/"
      - "cd /kernel/ramdisk/"
      - "ls -la /kernel"
      - "ls -la /kernel/ramdisk/"
      - "ls -la /kernel/smaug-custom-initram/"
      - "./build.sh"
      - "ls -la /kernel/ramdisk/"
      - "cd /kernel/linux-smaug/"
      - "make dragon_denvit_defconfig"
      - "bash getvendor.sh -f"
      - "make -j8"
      - "./build-image.sh"
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: /kernel/kitchen/*
    when
      event: tag
