workspace:
  base: /build/kernel
  path: /linux-smaug
pipeline:
  build:
    image: dvitali/android-build:feb-20
    commands:
      - "mkdir -p /build/kernel/kitchen"
      - "chown -R $UID:$UID /build"
      - "git clone https://github.com/denysvitali/ramdisk-builder /build/kernel/ramdisk"
      - "ln -s ramdisk.cpio.gz /build/kernel/ramdisk/custom-initramfs.cpio.gz"
      - "ls -la /build/kernel/ramdisk/"
      - "git clone https://github.com/denysvitali/smaug-custom-initram /build/kernel/smaug-custom-initram"
      - "ls -la /build/kernel/"
      - "cd /build/kernel/ramdisk/"
      - "mkdir /kernel"
      - "mount -o bind /build/kernel/ /kernel"
      - "ls -la /kernel"
      - "ls -la /kernel/ramdisk/"
      - "ls -la /build/kernel/ramdisk/"
      - "ls -la /build/kernel/smaug-custom-initram/"
      - "./build.sh"
      - "ls -la /build/kernel/ramdisk/"
      - "cd /build/kernel/linux-smaug/"
      - "make dragon_denvit_defconfig"
      - "bash getvendor.sh -f"
      - "make -j8"
      - "./build-image.sh"
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: /build/kernel/kitchen/*
